ALTER TABLE products ALTER COLUMN public_key DROP NOT NULL;
ALTER TABLE products ALTER COLUMN encrypted_private_key DROP NOT NULL;
ALTER TABLE products ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
ALTER TABLE licenses ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
